### ISSUE TITLE
Ignore Hub Failures

### ISSUE THREAD

**Issue by vjkoskela** [blackducksoftware/hub-gradle-plugin#16]
Much appreciated if you could port the ignore hub failure feature from the Maven Plugin () to the Gradle Plugin.

See: 
https://github.com/blackducksoftware/hub-maven-plugin/pull/4

However, please keep in mind this issue recently reported with the Maven implementation:
https://github.com/blackducksoftware/hub-maven-plugin/issues/7

Thank you,
Ville Koskela

**Comment by ekerwin** [comment]
This should be fixed in 3.3.0

**Comment by ekerwin** [comment]
Excuse me, this IS fixed in 3.3.0.

**Comment by vjkoskela** [comment]
Glad to hear it!

When you have time please update the documentation:
- https://github.com/blackducksoftware/hub-gradle-plugin/wiki

Also, there is page under the maven hub plugin titled "Hub-Maven-&-Gradle-Properties", it may need to be updated - or possibly renamed - as well.
- https://github.com/blackducksoftware/hub-maven-plugin/wiki/Hub-Maven-&-Gradle-Properties

Thanks!

**Comment by vjkoskela** [comment]
@ekerwin only up to version 3.20 of the hub-gradle-plugin appears to be in Maven Central:

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.blackducksoftware.integration%22%20AND%20a%3A%22hub-gradle-plugin%22

Was the above a type-o or has it not been released yet? 

Thanks,
Ville

**Comment by ekerwin** [comment]
Ville, thanks for pointing this out. For some reason, the staging repository on nexus (maven central) was only closed and not released. I've just released it manually so 3.3.0 should show up some time later today. Sorry about that!

**Comment by vjkoskela** [comment]
@ekerwin I'm afraid it's still not there; in my experience it should only take 10-15 min to appear in central:

http://central.maven.org/maven2/com/blackducksoftware/integration/hub-gradle-plugin/

Can you double check your release?

**Comment by ekerwin** [comment]
Sorry about this - thanks for bringing it to our attention. We are looking in to it. We are also planning on releasing 3.4.0 possibly today, so that might also clear this up and 3.3.0 might just be a phantom release.

**Comment by ekerwin** [comment]
I've just released 3.4.0 - let's hope it shows up in maven central with no issues. It will include all 3.3.x fixes as well as some new files for the output.

**Comment by ekerwin** [comment]
It looks like 3.4.0 is available - please check that and if all is good, we can close this issue down.

**Comment by ekerwin** [comment]
Haven't heard anything - I believe 3.4.0 did fix this. Please reopen if otherwise. Thanks!
